### PR TITLE
started the dinner recipe

### PR DESCRIPTION
**Pull request by kat-law**
the summer salad is looking a little bland. please help add more ingredients and instructions

## 🎯 Objective

Let's the create a salad

## 🛠️ Changes made
started a basic recipe 

## 👥 Who needs to review this Pull Request? 

_@mention some teammates to review your work._
_Pull Requests should include commits from each member of your group._

### CODE REVIEW

**Review by sydneychirls29 — APPROVED** [review]
This is a great start! Love the summer salad idea.

**Comment by mdubshere** [comment]
Perfect. Salad is great.

**Review by Nikiness — COMMENTED** [review]
Reviewed

**Comment by thisisvc** [comment]
This looks good!

**Pull request merged**
