### PR TITLE
I added a care instructions for the lettuce.

### PR DESCRIPTION
**Pull request by mdubshere**
## 🎯 Objective

I like nice lettuce and want to make sure people don't mess it up when they dry it. 

## 🛠️ Changes made

I added care instructions. 

## 👥 Who needs to review this Pull Request? 

@eliasspringer @kat-law

### CODE REVIEW

**Comment by eliasspringer** [comment]
Wow lettuce do this! Much better approach.

**Comment by thisisvc** [comment]
perfect!

**Comment by mdubshere** [comment]
Duplicate changes.

**Comment by kat-law** [comment]
Aw the lettuce will be intact

**Pull request closed without merging**
